### ISSUE TITLE
Publish to the plugin registry

### ISSUE THREAD

**Issue by tnguyen14** [gglukmann/wp-trigger-github#1]
Can this plugin be published to the wordpress plugin registry so I can install directly from within wordpress?

**Comment by gglukmann** [comment]
Do you still need it inside wordpress plugin registry?

**Comment by tnguyen14** [comment]
I am uploading it privately for now to have the changes I need. But once those changes are merged, I think it'd be good to have it in the registry.

**Comment by tnguyen14** [comment]
@gglukmann can this be published now?

**Comment by gglukmann** [comment]
I got the accept from wordpress, just have to upload everything through svn, I'll try to take time for that soon

**Comment by tnguyen14** [comment]
@gglukmann any update on this?

**Comment by gglukmann** [comment]
Done! Took some time :D https://wordpress.org/plugins/wp-trigger-github/
