### ISSUE TITLE
3 builds on every save of Page.

### ISSUE THREAD

**Issue by tommi-hack** [gglukmann/wp-trigger-github#5]
It always triggers 3 builds when saving a Page.

Tested on Wordpress 5.7

Also, badge url is wrong

it should have "actions/workflows" but has only "workflows" in it.

**Comment by gglukmann** [comment]
What has changed on WordPress 5.7 that it triggers build 3 times? Could you make a PR with a fix?

**Comment by tommi-hack** [comment]
Sadly I have no idea what has changed in 5.7. I have only one WP installation available and it is 5.7. And not a WP pro, I have no idea how it should be fixed.
But I will post here if I figure out the fix or the cause.

**Comment by tommi-hack** [comment]
most probably it is not related to your plugin. Closing the issue.
I took one of the forks that has separate button to deploy manually.
